= Bases de Datos I: Práctica 2
{docdate}

== Dependencias Funcionales

1. Dadas las siguientes relaciones, indicar cuáles son las dependencias
funcionales no triviales que se deberían cumplir.

a. alumne(nro_legajo, nombre, apellido, dni, carrera, facultad, materia,
nota_final).

b. empleade(legajo, nombre, apellido, dpto, legajo_jefe_dpto, f_ingreso,
salario).

2. Dada la relación
+
artículo(cod, descr, costo, precio, stock, prov)
+
y conjunto de dependencias funcionales
+
_F_ = {cod → descr stock, cod prov → costo, costo → precio, descr → cod},
+
indicar cuales de las siguientes dependencias funcionales se pueden
deducir de _F_ usando los axiomas de Armstrong. En caso de que no se
puedan deducir, demostrar mediante una instancia de la relación artículo
que sirva de contraejemplo.

a. cod prov → descr precio

b. cod → precio

c. descr → stock

d. precio → costo

e. descr prov → cod descr costo precio stock prov

3. Dada la relación _R(A, B, C, D, E)_. Cuáles de las siguientes
inferencias son válidas? Demostrar la validez de cada una usando las
reglas de Armstrong, en caso contrario encontrar algún contraejemplo.

a. { _A_ → _BC_, _C_ → _DE_ } ⊨ { _A_ → _ABCDE_ }

b. { _A_ → _B_, _B_ → _C_, _C_ → _D_ } ⊨ { _B_ → _A_ }

c. { _A_ → _B_, _B_ → _C_, _C_ → _D_, _D_ → _A_ } ⊨ { _B_ → _A_ }

d. { _A_ → _B_, _BD_ → _C_ } ⊨ { _AD_ → _BC_ }

e. { _AB_ → _C_, _C_ → _D_, _BD_ → _E_ } ⊨ { _A_ → _ABCDE_ }

4. Dada la relación _R(A, B, C, D, E)_ encontrar *todas* las claves de
_R_ con respecto a los siguientes conjuntos de dependencias funcionales.

a. { _A_ → _BC_, _C_ → _DE_ }

b. { _A_ → _B_, _B_ → _C_, _C_ → _D_ }

c. { _A_ → _B_, _B_ → _C_, _C_ → _D_, _D_ → _A_ }

d. { _A_ → _B_, _BD_ → _C_ }

e. { _AB_ → _C_, _C_ → _D_, _BD_ → _E_ }

5. Demostrar las reglas de unión y de pseudo transitividad usando las
reglas de Armstrong.

6. Hallar la clausura de atributos para cada uno de los siguientes
conjuntos de dependencias funcionales que aparecen a continuación.

a. Dado { _X_ → _YT_, _YW_ → _Z_, _TZ_ → _U_, _U_ → _V_ }, obtener _XW⁺_
y _X⁺_.

b. Dado { _X_ → _Y_, _YW_ → _Z_, _TZ_ → _U_, _U_ → _V_ }, obtener _XW⁺_
y _XWT⁺_.

c. Dado { _X_ → _Y_, _YW_ → _Z_, _TZ_ → _U_, _U_ → _V_, _V_ → _X_ },
obtener _U⁺_, _UW⁺_ y _W⁺_.

d. Dado { _X_ → _U_, _YW_ → _V_, _TZ_ → _U_, _U_ → _V_, _V_ → _W_, _S_ →
_TV_, _T_ → _X_ }, obtener _XY⁺_, _S⁺_ y _ST⁺_.

7. Dada la relación _R(A, B, C, D, E, F, G, H)_, hallar el cubrimiento
minimal de los siguientes conjuntos de dependencias funcionales, e
indicar cuáles de ellos son equivalentes entre sí.

a. { _A_ → _ABE_, _C_ → _D_, _E_ → _FG_, _AD_ → _EFG_ }

b. { _A_ → _BE_, _C_ → _D_, _E_ → _F_, _E_ → _G_, _AD_ → _EF_ }

c. { _A_ → _BE_, _B_ → _D_, _C_ → _D_, _E_ → _EFG_, _A_ → _BEF_ }

d. { _A_ → _BE_, _CH_ → _D_, _E_ → _F_, _E_ → _G_, _AD_ → _EF_ }

e. { _A_ → _BE_, _C_ → _DC_, _E_ → _EFG_, _E_ → _G_, _AD_ → _EFG_ }

8. Sea _R(A, B, C, D, E, F)_ y el conjunto de dependencias funcionales
_F_ = { _A_ → _CB_, _A_ → _F_, _C_ → _E_, _D_ → _E_, _F_ → _A_ }. Hallar
*todas* las claves—y ver que son minimales.

== Normalización

1. Sea la relación _R(A, B, C, D, E, F)_ y el conjunto de dependencias
funcionales F = { _A_ → _BC_, _A_ → _F_, _C_ → _E_, _D_ → _E_, _F_ → _A_
}.

a. Hallar las claves de _R_.

b. Decir en qué forma normal se encuentra _R_. Justificar.

2. Sea la relación _R(A, B, C, D, E, F, G, H, I)_ y el conjunto de
dependencias funcionales F = { _A_ → _BC_, _A_ → _F_, _C_ → _E_, _CD_ →
_EI_, _F_ → _GH_ }.

a. Hallar las claves de _R_.

b. Decir en qué forma normal se encuentra _R_. Justificar.

3. Dada la siguiente relación con su conjunto de dependencias
funcionales:
+
f1(piloto, escudería, circuito, cant_vueltas, long_circuito, año,
posición, tiempo)
+
piloto circuito año → posición tiempo
+
circuito → long_circuito
+
circuito año → cant_vueltas
+
piloto año → escudería
+
Indicar en qué forma normal se encuentra la relación f1.

4. Utilizando las dependencias funcionales que se identificaron en el
*Ejercicio 1b de Dependencias Funcionales*, indicar en que forma normal
se encuentra la relación empleade.

5. Hallar las claves e indicar en qué forma normal se encuentra la
relación _R(A, B, C, D, E, F, G)_ con respecto a los siguientes
conjuntos de dependencias funcionales:

a. F = { _A_ → _C_, _B_ → _D_, _E_ → _F_, _A_ → _G_ }.

b. F = { _A_ → _C_, _B_ → _D_, _B_ → _F_, _A_ → _G_, _A_ → _B_, _A_ →
_E_ }.

c. F = { _A_ → _C_, _B_ → _D_, _B_ → _F_, _A_ → _G_, _A_ → _B_ }.

d. F = { _ABE_ → _CDFG_, _E_ → _A_ }.

6. Para los ítems del *Ejercicio 7 de Dependencias Funcionales*,
descomponer a BCNF.

7. Descomponer a BCNF las relaciones de los *Ejercicios 1 y 2*.
