= Bases de Datos I: Práctica 3
{docdate}

== Álgebra Relacional

1. Dadas las siguientes relaciones, resolver usando álgebra relacional.
+
bote(bid, nombre, color)
+
marine(mid, nombre, puntaje, f_inscripcion)
+
alquiler(bid, mid, fecha)
+
reserva(bid, mid, fecha)

a. Obtener los nombres de los botes rojos.

b. Obtener los nombres de les marines que se inscribieron después del
2011-06-26.

c. Obtener los nombres de les marines que se inscribieron durante el año
2012.

d. Obtener los números de botes alquilados por le marine número 100.

e. Obtener los nombres de les marines que alquilaron el bote "Macross".

f. Obtener los nombres de les marines que alquilaron botes rojos.

g. Obtener los botes reservados para el 2011-06-26.

h. Obtener los botes disponibles para alquilar el 2011-06-26.

i. Obtener los nombres de les marines que no alquilaron ningún bote.

j. Obtener los nombres de les marines que alquilaron al menos dos botes.

k. Obtener los nombres de les marines que alquilaron sólo un bote.

l. Obtener los nombres de les marines que alquilaron todos los botes.

m. Obtener los nombres de les marines que alquilaron todos los botes
verdes.

n. Obtener las fechas en que hay botes reservados.

o. Obtener las fechas en que están reservados todos los botes.

2. Dadas las siguientes relaciones
+
gusta(bebedor, cerveza)
+
frecuenta(bebedor, bar)
+
sirve(bar, cerveza)
+
--
Suponer que:

- Todas las cervezas son servidas en al menos un bar.

- Todos los bebedores frecuentan al menos un bar.

- Todos los bares sirven al menos una cerveza.
--
+
Obtener mediante álgebra relacional:

a. Los nombres de todos los bares.

b. Los nombres de todos los bebedores.

c. Las cervezas que le gustan a Juan y que son servidas en el bar
Rockeria.

d. Los bares que sirven todas las cervezas que le gustan a Juan.

e. Los bares que sirven todas las cervezas que le gustan a Juan y a
Pedro

f. Los bebedores que van a bares que sólo sirven cervezas que les
gustan.

== SQL

*Resolver mediante SQL los ítems de los ejercicios anteriores.*
